name: example
description: A showcase of Muskey features.

publish_to: 'none'
version: 1.0.0

environment:
  sdk: ">=2.16.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  muskey:
    path: '../'

dev_dependencies:
  flutter_lints: ^1.0.0

flutter:
  uses-material-design: true
