name: muskey
description: An actually useful pattern matcher and field input formatter for Flutter.
version: 1.0.0
homepage: https://github.com/scisdev/muskey

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0
